# Generated by Django 5.1.1 on 2024-09-21 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Residuo',
            fields=[
                ('residuo_id', models.AutoField(primary_key=True, serialize=False)),
                ('residuo_descricao', models.CharField(max_length=255)),
                ('residuo_formula_quimica', models.CharField(max_length=255)),
                ('residuo_categoria', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tblresiduo',
            },
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('deposito_id', models.AutoField(primary_key=True, serialize=False)),
                ('deposito_descricao', models.CharField(max_length=255)),
                ('residuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycleapp.residuo')),
            ],
            options={
                'db_table': 'tbldeposito',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_parceiro', models.BooleanField(default=False)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
